services:
    kwc_newsletter.model.newsletters:
        class:   KwcNewsletter\Bundle\Model\Newsletters
        factory: ['Kwf_Model_Abstract', getInstance]
        arguments: ['KwcNewsletter\Bundle\Model\Newsletters']

    kwc_newsletter.model.subscribers:
            class:   KwcNewsletter\Bundle\Model\Subscribers
            factory: ['Kwf_Model_Abstract', getInstance]
            arguments: ['KwcNewsletter\Bundle\Model\Subscribers']

    kwc_newsletter.model.newsletter_queue_logs:
            class:   KwcNewsletter\Bundle\Model\NewsletterQueueLogs
            factory: ['Kwf_Model_Abstract', getInstance]
            arguments: ['KwcNewsletter\Bundle\Model\NewsletterQueueLogs']

    kwc_newsletter.model.deleted_subscriber_hashes:
            class:   KwcNewsletter\Bundle\Model\DeletedSubscriberHashes
            factory: ['Kwf_Model_Abstract', getInstance]
            arguments: ['KwcNewsletter\Bundle\Model\DeletedSubscriberHashes']

    kwc_newsletter.model.newsletter_runs:
            class:   KwcNewsletter\Bundle\Model\NewsletterRuns
            factory: ['Kwf_Model_Abstract', getInstance]
            arguments: ['KwcNewsletter\Bundle\Model\NewsletterRuns']
